name: Deploy to DO

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:

  deployment:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v --race ./...

      - name: Move to exec file to correct directory
        run: mv -f my-mini-checklist /usr/local/my-mini-checklist

      - name: Service Restart
        run: systemctl restart my-mini-checklist.service