name: Deploy to DO

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:

  deployment:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v --race ./...

      - name: Check the folder path
        run: pwd